import { Navbar } from "@/components/ui/navbar";
import { Provider } from "@/components/ui/provider";
import { Container, Flex } from "@chakra-ui/react";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        suppressHydrationWarning
      >
        <Provider>
          <Flex direction="column" minH="100vh">
            <Navbar />
            <Container as="main" maxW="100%" px={0} py={8} flex={1}>
              {children}
            </Container>
          </Flex>
        </Provider>
      </body>
    </html>
  );
}
